### ISSUE TITLE
Add your art

### ISSUE THREAD

**Issue by kevinesaa** [kevinesaa/H-ART-cktober-2020#13]
This is a repository for artists that want participate in Hacktober Fest. All kind of art is welcome, music, 3d models, writting, ilustration, etc. 

Check the [details](https://github.com/kevinesaa/H-ART-cktober-2020/blob/master/README-en.md)  and the [guidelines](https://github.com/kevinesaa/H-ART-cktober-2020/blob/master/CONTRIBUTING-en.md) before summit your pull request.

**Comment by annahothai** [comment]
Hey can I work on this? Do I need to make an artwork for the day's prompt or can I also make art for previous days' prompt too?

**Comment by kevinesaa** [comment]
@annahothai Sure! 
Feel free to forking the repo and make all the pull request that you want.
