### ISSUE TITLE
Traducir el Reame

### ISSUE THREAD

**Issue by kevinesaa** [kevinesaa/H-ART-cktober-2020#8]
Esta actividad consite en traducir el archivo [README-en.md](https://github.com/kevinesaa/H-ART-cktober-2020/blob/master/README-en.md), del español al inglés.

This activity consists of translating the file [README-en.md](https://github.com/kevinesaa/H-ART-cktober-2020/blob/master/README-en.md), from Spanish to English.

**Comment by Olsyx** [comment]
Me ocupo

**Comment by Olsyx** [comment]
En la página de hacktoberfest me dice que este repositorio no es elegible:
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

No sé si os lo han rechazo o está en trámite, pero por si acaso aviso ^^

**Comment by kevinesaa** [comment]
@Olsyx vale muchas gracias, ya busco a ver si hay que hacer algo adicional.
