### ISSUE TITLE
traducir el contributing

### ISSUE THREAD

**Issue by kevinesaa** [kevinesaa/H-ART-cktober-2020#9]
Esta actividad consite en traducir el archivo [CONTRIBUTING-en.md]https://github.com/kevinesaa/H-ART-cktober-2020/blob/master/CONTRIBUTING-en.md), del español al inglés.

This activity consists of translating the file [CONTRIBUTING-en.md]https://github.com/kevinesaa/H-ART-cktober-2020/blob/master/CONTRIBUTING-en.md), from Spanish to English.

**Comment by leandro-grg** [comment]
@kevinesaa podrías asignarme este issue? Me gustaría colaborar!

**Comment by kevinesaa** [comment]
@leandro-grg claro, muchas gracias
